Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -45,8 +45,12 @@ jobs:
           cd bin
           # 下载最新的 Xray
           LATEST_XRAY_URL=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | grep "browser_download_url.*Xray-linux-64.zip" | cut -d '"' -f 4)
+          echo "LATEST_XRAY_URL: $LATEST_XRAY_URL"  # 打印 URL
+          if [ -z "$LATEST_XRAY_URL" ]; then
+            echo "Error: LATEST_XRAY_URL is empty"
+            exit 1
+          fi
           curl -L -o Xray-linux-64.zip "$LATEST_XRAY_URL"
-          unzip Xray-linux-64.zip
           rm -f Xray-linux-64.zip geoip.dat geosite.dat
           # 下载最新的 geoip.dat 和 geosite.dat
           LATEST_GEOIP_URL=$(curl -s https://api.github.com/repos/Loyalsoldier/v2ray-rules-dat/releases/latest | grep "browser_download_url.*geoip.dat" | cut -d '"' -f 4)
